'use strict'

const MAX_GPS_ACCURACY_BUFFER = 30
const CIRCLE_RADIUS_MIN = 50
const CIRCLE_RADIUS_MAX = 2000
const RADIUS_PRESETS = [50, 100, 200, 300, 500, 1000, 2000]
const DEFAULT_CITY_ID = 'victoria-bc'

module.exports = {
  MAX_GPS_ACCURACY_BUFFER,
  CIRCLE_RADIUS_MIN,
  CIRCLE_RADIUS_MAX,
  RADIUS_PRESETS,
  DEFAULT_CITY_ID,
}
