'use strict'

const MAX_GPS_ACCURACY_BUFFER = 30
const CIRCLE_RADIUS_MIN = 50
const CIRCLE_RADIUS_MAX = 2000
const RADIUS_PRESETS = [50, 100, 200, 300, 500, 1000, 2000]
const DEFAULT_CITY_ID = 'victoria-bc'

// Polygon limits — mirror set_quest_boundary() in migration 015; keep in sync.
const POLYGON_MIN_VERTICES = 3
const POLYGON_MAX_VERTICES = 100
const POLYGON_MIN_AREA_M2 = 400
const POLYGON_MAX_AREA_M2 = 250000000

module.exports = {
  MAX_GPS_ACCURACY_BUFFER,
  CIRCLE_RADIUS_MIN,
  CIRCLE_RADIUS_MAX,
  RADIUS_PRESETS,
  DEFAULT_CITY_ID,
  POLYGON_MIN_VERTICES,
  POLYGON_MAX_VERTICES,
  POLYGON_MIN_AREA_M2,
  POLYGON_MAX_AREA_M2,
}
